Part1
Jon-MarkHampson/PFMCPP_Project2 pull request #1
Opened 2022-02-12 10:04 UTC by Jon-MarkHampson

2022-02-12 22:23 UTC, matkatmusic requested changes
Some of your functions still don't conform to the guideline of Name things what they are or what they do
It's very important to choose great names for your functions and variables.
you want your code to read as though you're reading instructions from a children's toy manual.
    processOutputGain(buffer);
    
    processOutputMeters(buffer);
    

    if( analyzerIsEnabled && !analyzerIsPreEq )
    {
        leftChannelSampleFifo.update(buffer);
        rightChannelSampleFifo.update(buffer);
    }
Without even knowing how these functions are implemented, can you infer what they do, based on the function names and variable names used?

You should be using this idea to pick names for your functions that include verbs in the name.
- [ ] revise

2022-02-12 22:23 UTC, matkatmusic commented on main.cpp
> +double stressLevel(bool doSport = false, int numberOfChildren = 5, bool didSchoolRun = true, double income = 45678.23, bool happyWithJob = false, int numberOfFriends = 4)
Add a verb to these function names
- [ ] revise

2022-02-12 22:23 UTC, matkatmusic commented on main.cpp
> +{
Add a verb to this function names
- [ ] revise

2022-02-12 22:23 UTC, matkatmusic commented on main.cpp
> +{
Add a verb to this function names
- [ ] revise

2022-02-13 01:46 UTC, Jon-MarkHampson commented
requested revisions completed

2022-02-13 07:15 UTC, matkatmusic requested changes
Your project produces warnings and crashes when compiled and executed.

2022-02-13 07:15 UTC, matkatmusic commented on main.cpp
> +{
This function name has no verb in it.
the first function argument is misspelled.
- [ ] revise

2022-02-13 07:15 UTC, matkatmusic commented on main.cpp
> +}
This function doesn't return a value and it is declared that it should.
The function name doesn't conform to the course coding standard.
- [ ] revise

2022-02-13 07:15 UTC, matkatmusic commented on main.cpp
> +{
The function name doesn't conform to the course coding standard.
- [ ] revise

2022-02-13 21:19 UTC, matkatmusic approved these changes

2022-02-13 21:19 UTC, merged